[package]
name = "qiro_finance_lending_vault"
version = "1.0.0"
authors = []

[addresses]
qiro='8f7e0393db7f8405e1c21b179ff3b3221dac3b166a1bd72bd6460d75881bb1d6'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
