[package]
name = "qiro_finance_lending_vault"
version = "1.0.0"
authors = []

[addresses]
qiro='98d3f596cfbff2d843da07931943eb122a316c7f44762bf1aaff65f942786edd'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
