[package]
name = "qiro_finance_lending_vault"
version = "1.0.0"
authors = []

[addresses]
qiro='9ec55d144965d6e236aab62a08e19f2b611cd0ccf84b0f0d31863aac061ba12b'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
