[package]
name = "qiro_finance_lending_vault"
version = "1.0.0"
authors = []

[addresses]
qiro='9d88c68a4f5ab329edada2b5b795ebcad4da2341538ddbf8c993b6db9bf46586'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
